### ISSUE TITLE
Using this with event handlers in mercury

### ISSUE THREAD

**Issue by alessioalex** [TimBeyer/html-to-vdom#7]
Hey,

I was wondering how can I use this library and still define event handlers (functions) for stuff?

I'm reffering to the event handlers in mercury especially: https://github.com/Raynos/mercury/blob/master/docs/faq.md#how-do-i-do-custom-event-handling-in-mercury

Any tips?

Thanks a lot.

**Comment by TimBeyer** [comment]
Hey, sorry for replying so late.  
I cannot really see how to do this currently. You'd have to parse the `ev-event` etc attributes and then do some magic to wire them up. But then how to establish a mapping between your callbacks and those elements?  
I wouldn't say it's impossible, but I believe it's out of scope for this library.
It's quite specific to `mercury` and not generally available for `virtual-dom`.  

Maybe you have a proposal for an extension interface so that others could implement features like this based on `html-to-vdom`?
